### ISSUE TITLE
Docker instance fails when using self-hosted models llama.cpp

### ISSUE THREAD

**Issue by ManuXD32** [Josh-XT/Agent-LLM#143]
### Description

After setting everything up in docker to use a local model instead of OpenAI's, I try to start a task with the agent, everything seems to work but the model never loads, it downloads It's pytorch things and all of that and then you only get one more output:
`Using embedded DuckDB with persistence: data will be stored in: agents/Agent-LLM/memories
`
Then It just stops the docker backend instance.

### Steps to Reproduce the Bug

1. change docker-compose.yml to get your own models into docker
`version: "3.8"
services:
  frontend:
    image: ghcr.io/josh-xt/agent-llm-frontend
    init: true
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://backend:7437}
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/josh-xt/agent-llm-backend
    init: true
    env_file:
      - .env
    ports:
      - "7437:7437"
    volumes: 
      - ./:/app:rw
`
2. Change .env file to point to the model's path and setup the AI provider:
`# =========================
# AI PROVIDER CONFIG
# =========================
AI_PROVIDER=llamacpp
AI_MODEL=default
AI_TEMPERATURE=0.2
MAX_TOKENS=2000

# =========================
# AI PROVIDER: LLAMACPP
# =========================
MODEL_PATH=./models/13b-vicuna.bin`
3. Start the docker compose file 
4. Go to your localhost
5. Setup an agent task and wait for everything to fall apart hahaha
6. Providers llamacpp also returns error 404 (it also happens when i run it on a virtual machine but that's another thing to open an issue about)

### Expected Behavior

To start the task

### Actual Behavior

Crashes with this output:
`Using embedded DuckDB with persistence: data will be stored in: agents/Agent-LLM/memories
`

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Anyone using docker and llamacpp able to chime in?  I believe I've seen some people using it like this but I've only personally tested llamacpp locally.

**Comment by nbdy** [comment]
I had to to change my docker-compose.yml to:
```yaml
version: "3.8"
services:
  frontend:
    # image: ghcr.io/josh-xt/agent-llm-frontend
    build: ./frontend
    init: true
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://backend:7437}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    # image: ghcr.io/josh-xt/agent-llm-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    init: true
    env_file:
      - .env
    ports:
      - "7437:7437"
    volumes: # Optional persistent data
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - /media/safe/dl/llama/bin:/model:rw
```

Notice how instead of `image:` `build:` is now in use and NEXT_PUBLIC_API_URI has a different port.
Also notice how I've added a new volume to a directory where the models are stored.
I had to use a gglm converted model. If you just use `gpt4all-lora-quantized.bin` it will run but throw an error as soon as you instruct your agent.

So I've also adjusted the MODEL_PATH of the .env file to `MODEL_PATH=/model/ggml-gpt4all-l13b-snoozy.bin`.
Also I've changed the AI_PROVIDER_URI to `AI_PROVIDER_URI=http://127.0.0.1:7437`.

Hope it helps someone.
